runtime: python38

handlers:

- url: /
  script: auto
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /lib
  static_dir: lib
  secure: always

- url: /package
  static_dir: package
  secure: always

- url: /docs
  static_dir: docs
  secure: always

- url: /api/.*
  script: auto
  secure: always
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  secure: always
